import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { initStatsig } from "./initStatsig";
import { cookies } from "next/headers";
import StatsigProvider from "./StatsigProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  // grab the stable id we generated in the middleware to use for both the server and client statsig
  const stableID = cookieStore.get('statsigStableId')?.value ?? '';
  const user = {
    customIDs: {
      stableID,
    },
  };
  const statsigValues = await initStatsig(user);

  return (
    <html lang="en">
      <body className={inter.className}>
        <StatsigProvider user={user} values={statsigValues}>
          {children}
        </StatsigProvider>
      </body>
    </html>
  );
}
